Repository explosivegaming/scenario, pull requests merged in 2020-02, with the labels that each got.

#137 adding auto-station naming (suggested by cooldude) try 2
  config/_file_loader.lua
  modules/addons/station-auto-name.lua
Labels: Feature Request, In Progress

#141 Fix Spawn Items Equal 0
  modules/addons/advanced-start.lua
Labels: Awaiting Review, Bug

#142 Fixed chat popup for players with - in name
  modules/addons/chat-popups.lua
Labels: Awaiting Review, Bug

#140 Added Async Core Module
  config/chat_reply.lua
  expcore/async.lua
  expcore/permission_groups.lua
  expcore/roles.lua
  expcore/sudo.lua
  locale/en/addons.cfg
  modules/commands/interface.lua
Labels: Awaiting Review
